version: '2.1'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:1.3.1
    environment:
      - AWS_ACCESS_KEY_ID=dummyaccess
      - AWS_SECRET_ACCESS_KEY=dummysecret
      - AWS_DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=${LOCALSTACK_HOSTNAME}
      - SERVICES=${LOCALSTACK_SERVICES}
      - LS_LOG=info
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:4566/_localstack/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    expose:
      - 4566
    volumes:
      - ./localstack/kms.sh:/docker-entrypoint-initaws.d/kms.sh

  cucumber-tests:
    image: ${MAVEN_IMAGE}
    environment:
      - AWS_ACCESS_KEY_ID=dummyaccess
      - AWS_SECRET_ACCESS_KEY=dummysecret
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: /bin/bash -c
    command:
      - |
        sleep 5 #wait for keys to be created once localstack services are available (aws cli not available)
        mvn -Dtest=uk.gov.dwp.health.esao.verified.integration.RunCukesTest ${MVN_OPTS} ${MVN_CLI_OPTS} test
    working_dir: /usr/src
    depends_on:
      localstack:
        condition: service_healthy
    volumes:
      - .:/usr/src
      - ${MVN_M2}:/root/.m2
      - ${MVN_SETTINGS_FILE}:/root/.m2/settings.xml
