server:
  applicationConnectors:
  - type: http
    port: 9501
  adminConnectors:
  - type: http
    port: 0
  requestLog:
    type: external

sqsConfiguration:
  s3EndpointOverride: "http://localhost:4572"
  endpointOverride: "http://localhost:4576"
  pathStyleAccessEnabled: true
  s3BucketName: null
  region: US_EAST_1

snsConfiguration:
  s3EndpointOverride: "http://localhost:4572"
  endpointOverride: "http://localhost:4575"
  pathStyleAccessEnabled: true
  s3BucketName: null
  region: US_EAST_1

kmsQueueCryptoConfiguration:
  kmsEndpointOverride: http://localhost:5678
  dataKeyRequestId: test_request_id

sqsQueueName: esa-robotics-queue

snsTopicName: esa-drs-topic
snsRoutingKey: sns.verified.submission
snsSubject: verified-esa-claim
snsEncryptMessages: false

caseServiceApplicationEndpoint: http://localhost:3010/v1/cases/:{caseId}/application
caseServiceQueryEndpoint: http://localhost:3010/v1/cases/:{caseId}
caseServiceParameter: caseId

caseServiceTruststoreFile: null
caseServiceTruststorePass: null
caseServiceKeystoreFile: null
caseServiceKeystorePass: null

logging:
  level: INFO
  loggers:
    "uk.gov": DEBUG
